---
layout: page
title: "R ART"
subtitle: "색상 팔레트(palette)"
author:
  name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
  url: https://www.facebook.com/groups/tidyverse/
  affiliation: Tidyverse Korea
  affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```



# 이미지에서 팔레트 제작 {#extract-color-palette}

[행정안전부 어린이](https://www.mois.go.kr/chd/sub/a05/birth/screen.do) 웹사이트에 우리나라 국가상징 태극기 이미지를 다운로드 받아 대한민국 팔레트를 제작해보자. 먼저 국기 이미지 파일을 다운로드 받아 로컬 컴퓨터에 저장하고 이를 이미지 팩키지로 불러와서 시각화보자.
원본 이미지 파일 크기가 너무 커서 빠른 처리를 위해서 파일 크기를 줄인다. 이때 `image_scale()` 함수를 사용한다.

```{r install-palette}
# install.packages("colorfindr")
library(tidyverse)
library(colorfindr)
library(magick)

download.file(url='https://www.mois.go.kr/cmm/fms/FileDown.do?atchFileId=FILE_000000000010893&fileSn=0', destfile = "fig/korean_flag.zip", mode = "wb")

unzip("fig/korean_flag.zip", overwrite = TRUE, exdir = "fig/flag")

korean_flag <- image_read("fig/flag/태극기.jpg")

korean_flag_small <- korean_flag %>% 
  image_scale("300x200!")

korean_flag_small

korean_flag_small %>% 
  image_write("fig/korean_flag.jpg")
```

대한민국 국기에서 색상을 추출하고 이를 팔레트로 제작한다.

```{r make-palette}
flag_palette <- get_colors(
  img = "fig/korean_flag.jpg",
  top_n = 4,
) %>%
  make_palette(n = 4)

flag_palette
```


# 팔레트 색상 사용 [^tutorial-colorfindr] {#use-color-palette}

[^tutorial-colorfindr]: [Portrait of a ggplot on fire ](https://github.com/annahensch/R-tutorials/blob/master/ggplot-on-fire.md)

태극기에서 추출한 색상을 활용하여 `ggplot`으로 시각화한다.

```{r colorfindr-tutorial}
library(palmerpenguins)

penguins %>% 
  na.omit() %>% 
  ggplot(aes(flipper_length_mm, fill = species)) +
  geom_density(alpha = 0.8, color =NA) + 
  theme_dark() +
  scale_fill_manual(values = flag_palette)
```

