---
layout: page
title: "R ART"
subtitle: "문자로 경로 그리기"
author:
  name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
  url: https://www.facebook.com/groups/tidyverse/
  affiliation: Tidyverse Korea
  affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```



# `string2path` 팩키지 [^rust-string2path] {#string2path}

[^rust-string2path]: [`string2path`](https://github.com/yutannihilation/string2path)

먼저 `systemfonts::system_fonts()` 명령어로 폰트가 설치된 경로명을 확인한다. 그리고 나서 해당 문자를 `ggplot`으로 시각화한다.


```{r install-string2path}
# devtools::install_github("yutannihilation/string2path")
library(tidyverse)
library(string2path)

systemfonts::system_fonts() %>% 
  filter(str_detect(name, "Nanum"))

string_df <- string2path("윤영아 !!!", "C:\\WINDOWS\\Fonts\\NanumGothicCoding.ttf")

string_df <- tibble::rowid_to_column(string_df)

ggplot(string_df) +
  geom_path(aes(x, y, group = id)) +
  theme_void() +
  coord_equal()
```

애니메이션으로 제작해 보자.

```{r install-string2path-animate}
library(gganimate)

ggplot(string_df) +
  geom_path(aes(x, y, group = id), size = 2, colour = "blue", lineend = "round") +
  theme_void() +
  coord_equal() +
  transition_reveal(rowid)
```


# `Seoul R Meetup` 로고? {#seoul-R-meetup}

[Seoul R Meetup Group](https://www.meetup.com/seoul-r-meetup/)의 글자를 나눔바른펜 글꼴로 시각화해보자.

```{r seoul-r-meetup}

seoul_df <- string2path("Seoul R Meetup", "C:\\WINDOWS\\Fonts\\NanumBarunpenB.ttf")

seoul_df <- tibble::rowid_to_column(seoul_df)

ggplot(seoul_df) +
  geom_path(aes(x, y, group = id)) +
  theme_void() +
  coord_equal()
```

애니메이션으로 제작해 보자.

```{r seoul-r-meetup-animate}
ggplot(seoul_df) +
  geom_path(aes(x, y, group = id), size = 2, colour = "black", lineend = "round") +
  theme_void() +
  coord_equal() +
  transition_reveal(rowid)
```
